---
- name: Configurimg httpd.conf
  template:
    src: httpd.conf.j2
    dest: "{{ Jboss_Home }}/jws/httpd/conf/httpd.conf"
    mode: 777
- name: Configuring mod_cluster.conf
  template:
    src: solartis_mod_config.conf.j2
    dest: "{{ Jboss_Home }}/jws/httpd/solartis.conf/kb.conf.d/solartis_mod_config.conf"
    mode: 777
- name: mime file Creation
  command : touch /etc/mime.types
- name: Configuring apachectl
  template:
    src: apachectl.j2
    dest: "{{ Jboss_Home }}/jws/httpd/sbin/apachectl"
    mode: 777
- name: Configuring base.conf
  template:
    src: 00-base.conf.j2
    dest: "{{ Jboss_Home }}/jws/httpd/conf.modules.d/00-base.conf"

   
